[package]
name = "frontend"
version = "0.1.0"
authors = ["Naum Azeredo <naumazeredo@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2"
models = { path = "../models" }

[lib]
crate-type = ["cdylib", "rlib"]
