[package]
name = "models"
version = "0.1.0"
authors = ["Naum Azeredo <naumazeredo@gmail.com>"]
edition = "2018"

[dependencies]
parking_lot = "0.11"
serde = { version = "1.0", features = ["derive"] }
